# name: AWS環境デプロイ
# on:
#     push:
#         # test,staging,prodブランチの場合にのみこのjob設定を使ってAWS環境にデプロイ
#         branches: [ prod,staging,test ]
# jobs:
#     deploy:
#         runs-on: ubuntu-latest
#         steps:
#             -   name: Configure AWS Credentials
#                 uses: aws-actions/configure-aws-credentials@v1
#                 with:
#                     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#                     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#                     aws-region: "ap-northeast-1"
#                     role-to-assume: "arn:aws:iam::740636045070:role/hr-deployer" # hr-workspacesアカウントのhr-deployer
#                     role-duration-seconds: 3600
#                     role-session-name: "unchike-worklog@GitHubActions"

#             -   name: checkout source
#                 uses: actions/checkout@v2

#             -   name: Set up JDK 11
#                 uses: actions/setup-java@v1
#                 with:
#                     java-version: 11

#             -   uses: actions/setup-node@v1
#                 with:
#                     node-version: "14"

#             -   name: Cache for node_modules
#                 uses: actions/cache@v2
#                 with:
#                     path: "**/node_modules"
#                     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

#             -   name: docker-compose
#                 run: docker-compose up -d

#             -   name: clean up
#                 run: sh ./gradlew clean

#             -   name: build with gradle without test
#                 run: sh ./gradlew build -x test

#             -   name: build ui project by npm
#                 # GITHUB_REF変数からブランチ名を取得してnpmコマンドを組み立てる
#                 run: cd ./unchike-worklog-front && npm install && npm run generate:${GITHUB_REF##*/}

#             -   name: install aws-cdk
#                 run: npm install -g aws-cdk

#             -   name: cdk version
#                 run: cdk --version

#             -   name: npm install (iacだけ)
#                 run: cd ./unchike-worklog-iac && npm install
#                 env:
#                     AWS_DEFAULT_REGION: "ap-northeast-1"

#             -   name: cdk synth
#                 run: cd ./unchike-worklog-iac && cdk synth
#                 env:
#                     AWS_DEFAULT_REGION: "ap-northeast-1"

#             -   name: cdk diff
#                 run: cd ./unchike-worklog-iac && cdk diff
#                 env:
#                    AWS_DEFAULT_REGION: "ap-northeast-1"

# #            -   name: cdk bootstrap
# #                run: cd ./unchike-worklog-iac && cdk bootstrap
# #                env:
# #                    AWS_DEFAULT_REGION: "ap-northeast-1"

#             -   name: cdk deploy
#                 run: cd ./unchike-worklog-iac && cdk deploy --require-approval never
#                 env:
#                     AWS_DEFAULT_REGION: "ap-northeast-1"